// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplicationAdd(arg1:main.Application):Promise<void>;

export function ApplicationList():Promise<Array<main.Application>>;

export function ApplicationStart(arg1:string):Promise<void>;

export function ApplicationStatus(arg1:string):Promise<boolean>;

export function Greet(arg1:string):Promise<string>;
