// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationAdd(arg1) {
  return window['go']['main']['App']['ApplicationAdd'](arg1);
}

export function ApplicationDelete(arg1) {
  return window['go']['main']['App']['ApplicationDelete'](arg1);
}

export function ApplicationList() {
  return window['go']['main']['App']['ApplicationList']();
}

export function ApplicationStart(arg1) {
  return window['go']['main']['App']['ApplicationStart'](arg1);
}

export function ApplicationStatus(arg1) {
  return window['go']['main']['App']['ApplicationStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
